[package]
name = "Whiteboard"
version = "0.0.1.0"

[[bin]]
default = true
name = "NewRelease"
includedir = "src"

[[bin]]
name = "Stable"
includedir = "src"

[[test]]
name = "example_test"
srcdir = "tests/example_test"
includedir = "tests/example_test"