[package]
name = "Whiteboard"
version = "0.1.1.0"

[[bin]]
default = true
name = "NewRelease"
includedir = "src"

[[bin]]
name = "Stable"
includedir = "src"

[[bin]]
name = "NullStrTest"
srcdir = "test/null_str_test"
includedir = "src"
