[package]
name = "Whiteboard"
version = "0.0.1.1"

[[bin]]
default = true
name = "Release"
cc = "gcc"
ld = "gcc"
ccargs = "-O2 -Wall -Wextra"
ldargs = "-B gcc"
includedir = "src"

[[bin]]
name = "StaticRelease"
cc = "gcc"
ld = "gcc"
ccargs = "-O3 -Wall -Wextra"
ldargs = "-static -B gcc"
includedir = "src"

[[bin]]
name = "Debug"
includedir = "src"

[[test]]
name = "example_test"
srcdir = "tests/example_test"
includedir = "tests/example_test"
programincludedir = "src"
