[package]
name = "Whiteboard"
version = "0.0.1.0"

[[bin]]
default = true
name = "NewRelease"
ccargs = "-g -O2 -Wall -Wextra" # This should also be the default value if not provided
ldargs = "-B gcc" # This should also be the default value if not provided
includedir = "src"

[[bin]]
name = "Stable"
includedir = "src"

[[test]]
name = "example_test"
srcdir = "tests/example_test"
includedir = "tests/example_test"
programincludedir = "src"
